### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by IcemanCharlie** [boeyum/WizLan#5]
When I’m trying to add anything from your app it tells me unknown error every time.

**Comment by boeyum** [comment]
Hi. To help you, I need to know what you are trying to connect to and what device driver. In general, I can say that there are two types of Wiz devices. The brand app was initially built is from the company Wiz Connected. The other company that supplies bulbs called Wiz is Philips. As far as I know, these two companies have the same owners. I have tested WIZ light bulbs from Philips (of a newer type) in the app and these worked in my network, but seemed to have longer response time a wiz connected light bulb. This means that the capacity and speed of the WiFi network can affect functionality when using bulbs from Philips.

**Comment by boeyum** [comment]
There are a new version out with bux fixes. This will solve the problem if it's not a network issue.
